name: "Commit generated C# code"

on:
    workflow_call:

permissions: write-all

jobs:
    commit-job:
        name: "Commit generated C# code"
        runs-on: ubuntu-20.04
        if: github.actor == 'dependabot[bot]'

        steps:
            - name: "Clone Git repository"
              uses: actions/checkout@v4
              with:
                  submodules: "true"

            - name: "Download changes to commit"
              uses: actions/download-artifact@v4
              with:
                  name: "bindgen-cs"
                  path: "./src/cs/production/Tracy/Generated"

            - name: "Add + commit + push (if necessary)"
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: "Synthetic-Dev"
                  author_email: "Synthetic-Dev@users.noreply.github.com"
                  message: "Update C# bindings"
